Q: Can we predict the player's plyed hours with their experience, age, and gender?

1) Data Description
- number of observations: 196
- number of variables: 9
- name and type of variables: experience (categorical), subscribe (categorical), hashedEmail (categorical), played_hours (numerical), name (categorical), gender (categorical), age (numerical), individualid (unknown), organizationName (unknown)
- meaning of variables:
  - experience: player's approximate level in game (beginner, regular, amateur, pro, veteran)
  - subscribe: whether each player subscribe to a game-related newsletter
  - hashedEmail: player's hashed email
  - played_hours: player's played hour
  - name: player's name
  - gender: player's gender
  - age: player's age
- any issues seen in the data:
  - last two columns does not contain any information
  - played hours 
- potential issues:
  - players with unspecified gender may limit the use of the gender variable
- how data were collected: a research group set up a MineCraft server Links to an external site, and players actions are recorded as they navigate through the world.

2) Question

Question 2: We would like to know which "kinds" of players are most likely to contribute a large amount of data so that we can target those players in our recruiting efforts.
- response variable: highest contributor 
- explanatory variables: experience, played hours, gender, age

The data will help us address the question of interest because it contains significant information of players, which could help us identify the common factor ("kinds") of players that contributes the most.
Th data set will be cleared up by only selecting/filtering columns(variables) we need.

3) Exploratory Data Analysis and Visualization
To load the dataset into Python, following command will be used:

In [1]:
import pandas as pd
players = pd.read_csv("https://drive.google.com/uc?export=download&id=1Mw9vW0hjTJwRWx0bDXiSpYsO3gKogaPz")
players

,experience,subscribe,hashedEmail,played_hours,name,gender,age,individualId,organizationName
0,Pro,True,f6daba428a5e19a3d47574858c13550499be23603422e6...,30.3,Morgan,Male,9,NaN,NaN
1,Veteran,True,f3c813577c458ba0dfef80996f8f32c93b6e8af1fa9397...,3.8,Christian,Male,17,NaN,NaN
2,Veteran,False,b674dd7ee0d24096d1c019615ce4d12b20fcbff12d79d3...,0.0,Blake,Male,17,NaN,NaN
3,Amateur,True,23fe711e0e3b77f1da7aa221ab1192afe21648d47d2b4f...,0.7,Flora,Female,21,NaN,NaN
4,Regular,True,7dc01f10bf20671ecfccdac23812b1b415acd42c2147cb...,0.1,Kylie,Male,21,NaN,NaN
...,...,...,...,...,...,...,...,...,...
191,Amateur,True,b6e9e593b9ec51c5e335457341c324c34a2239531e1890...,0.0,Bailey,Female,17,NaN,NaN
192,Veteran,False,71453e425f07d10da4fa2b349c83e73ccdf0fb3312f778...,0.3,Pascal,Male,22,NaN,NaN
193,Amateur,False,d572f391d452b76ea2d7e5e53a3d38bfd7499c7399db29...,0.0,Dylan,Prefer not to say,17,NaN,NaN
194,Amateur,False,f19e136ddde68f365afc860c725ccff54307dedd13968e...,2.3,Harlow,Male,17,NaN,NaN
195,Pro,True,d9473710057f7d42f36570f0be83817a4eea614029ff90...,0.2,Ahmed,Other,91,NaN,NaN

Minimum necessary wrangling:

In [2]:
players_clean = players.iloc[:, :7]
players_clean

players_clean["hashedEmail"].str.split("/", expand=True)
players_tidy = players_clean.drop(columns=["hashedEmail"])
players_tidy

    experience  subscribe  played_hours       name             gender  age
0          Pro       True          30.3     Morgan               Male    9
1      Veteran       True           3.8  Christian               Male   17
2      Veteran      False           0.0      Blake               Male   17
3      Amateur       True           0.7      Flora             Female   21
4      Regular       True           0.1      Kylie               Male   21
..         ...        ...           ...        ...                ...  ...
191    Amateur       True           0.0     Bailey             Female   17
192    Veteran      False           0.3     Pascal               Male   22
193    Amateur      False           0.0      Dylan  Prefer not to say   17
194    Amateur      False           2.3     Harlow               Male   17
195        Pro       True           0.2      Ahmed              Other   91

[196 rows x 6 columns]

Explanatory visualizations:

In [3]:
import altair as alt
players_hrs_age = alt.Chart(players_tidy).mark_circle(opacity=0.4).encode(x=alt.X("age").title("Player's Age"), y=alt.Y("played_hours").title("Played Hours"))
players_hrs_age

players_hrs_gender = alt.Chart(players_tidy).mark_circle(opacity=0.4).encode(x=alt.X("gender").title("Player's Gender"), y=alt.Y("played_hours").title("Played Hours"))
players_hrs_gender

players_hrs_exp = alt.Chart(players_tidy).mark_circle(opacity=0.4).encode(x=alt.X("experience").title("Player's level"), y=alt.Y("played_hours").title("Played Hours"))
players_hrs_exp

alt.Chart(...)

From this visualizations, we know that the data varies so much that when using scatter plot, the data is not comparable unless additional code is used to standardize the data, such as log.

4) Methods and Plan
To address the question of interest, knn-regression will be used. This method is appropriate because knn-regression predicts numerical values and our question wants to predict played hours and how certain characteristics of a player contributes to the amount of game played. The potential limitation and weakness to this method is that the data may vary a lot, as there is some missing information in the dataset, making it harder to interpret the data. Therefore, we must standardize the data before passing it on to Python. To compare the model, we will split the data into a training set and test set to effectively compare the predicted values and known values. We will use random seeds to prevent bias and make sure the data selected are randomly selected.